/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.multi.project.app;

import hello.multi.project.list.LinkedList;

import static hello.multi.project.utilities.StringUtils.join;
import static hello.multi.project.utilities.StringUtils.split;
import static hello.multi.project.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
        System.out.println("Hey darling");
    }
}
